# shellcheck shell=bash
# preflight.sh - fail fast, with a readable report, before touching anything.

preflight_run() {
    need_root

    case "${RHEL_MAJOR:-}" in
        7|8|9|10) ui_ok "Supported OS: $OS_PRETTY" ;;
        *)        die "unsupported OS '$OS_PRETTY' - SC2 supports RHEL 7, 8, 9 and 10 only" ;;
    esac

    [ "$ARCH" = "x86_64" ] || die "unsupported architecture '$ARCH' - SC2 is x86_64 only"

    # Bundle integrity (sha256sums is generated by build/build-bundle.sh)
    if [ -f "$SC2_ROOT/sha256sums" ]; then
        ( cd "$SC2_ROOT" && sha256sum --quiet -c sha256sums >/dev/null 2>&1 ) \
            || die "bundle integrity check failed - the SC2 bundle is corrupted or modified"
        ui_ok "Bundle integrity verified"
    else
        ui_warn "No sha256sums manifest in bundle; skipping integrity check"
    fi

    # Disk space: loaded images take roughly the archive size again, plus overhead.
    local store="/var/lib/containers"
    [ "$ENGINE" = docker ] && store="/var/lib/docker"
    local store_parent img_kb need_kb avail_kb
    store_parent="$store"
    while [ ! -d "$store_parent" ]; do store_parent="$(dirname "$store_parent")"; done
    img_kb="$(du -sk "$SC2_ROOT/images" 2>/dev/null | awk '{print $1}')"
    img_kb="${img_kb:-0}"
    need_kb=$(( img_kb * 2 + 300 * 1024 ))
    avail_kb="$(df -Pk "$store_parent" | awk 'NR==2 {print $4}')"
    if [ "${avail_kb:-0}" -lt "$need_kb" ]; then
        die "not enough disk space for $store: need ~$(( need_kb / 1024 ))MB, have $(( avail_kb / 1024 ))MB"
    fi
    ui_ok "Disk space OK ($(( avail_kb / 1024 ))MB free for $store)"

    # STIG systems commonly mount /var with noexec - container runtimes break there.
    local mp
    mp="$(df -P "$store_parent" | awk 'NR==2 {print $6}')"
    if awk -v mp="$mp" '$2 == mp { print $4 }' /proc/mounts | grep -qw noexec; then
        die "$mp is mounted noexec - container storage at $store cannot work there. Relocate storage or remount."
    fi

    case "$SELINUX_MODE" in
        Enforcing)  ui_ok "SELinux enforcing (SC2 will not change this)" ;;
        Permissive) ui_warn "SELinux is permissive" ;;
        *)          ui_warn "SELinux is $SELINUX_MODE" ;;
    esac
    [ "$FIPS_MODE" = on ] && ui_log "FIPS mode is enabled (supported)"
    [ "$FAPOLICYD" = active ] && ui_log "fapolicyd is active - SC2 will register its binaries as trusted"
    [ "$FIREWALL" = none ] && ui_warn "No active firewall detected - port rules will be skipped"

    bundle_validate

    # every bundled compose file must convert cleanly before we touch anything
    local app napps=0
    for app in $(apps_available); do
        if [ -f "$SC2_ROOT/apps/$app/docker-compose.yml" ]; then
            compose_validate "$SC2_ROOT/apps/$app/docker-compose.yml"
            napps=$(( napps + 1 ))
        fi
    done
    [ "$napps" -gt 0 ] && ui_ok "$napps compose file(s) validated"

    ui_ok "Preflight passed"
}
